function createfigure(cdata1)
%CREATEFIGURE(CDATA1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 30-Mar-2013 18:09:23

% Create figure
figure1 = figure('XVisual',...
    '0x22 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)',...
    'Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,...
    'YTickLabel',['0    ';'5000 ';'10000';'15000';'20000';'     '],...
    'Layer','top',...
    'FontSize',16);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-0.00290249433106576 7.10820861678005]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-5.38593063019052 22055.3859306302]);
box(axes1,'on');
hold(axes1,'all');

% Create image
image([0 7.10530612244898],[0 22050],cdata1,'Parent',axes1,...
    'CDataMapping','scaled');

% Create title
title('Evolving Freight Train','Interpreter','latex','FontSize',20,...
    'FontName','Arial');

% Create xlabel
xlabel('Time (s)','Interpreter','latex','FontSize',20,'FontName','Arial');

% Create ylabel
ylabel('Frequency (Hz)','Interpreter','latex','FontSize',20,...
    'FontName','Arial');

% Create colorbar
colorbar('peer',axes1);

